### ISSUE TITLE
Error when running download_345M.sh (download_345.sh does not exist)

### ISSUE THREAD

**Issue by Midnight1938** [BlackDChase/scrolls#1]
python3: can't open file 'download_model.sh': [Errno 2] No such file or directory
mv: cannot stat '../conditional_genration.sh': No such file or directory

**Comment by BlackDChase** [comment]
https://github.com/BlackDChase/scrolls/blob/master/download_345M.py, It downloads gpt-2's 345M model.
(It was sh before)
